### ISSUE TITLE
AWS 서버에 build, deploy할 때 유의사항

### ISSUE THREAD

**Issue by donggrii** [HaiyoreNyarukoSan/portfolio-for-portfolio#41]
- 로그인/회원가입 기능(OAuth2) 추가하기 전 정상 작동하였으나, 기능을 추가하고 AWS에 배포했을 때 `Internal Server Error` 등이 발생

### 해결방법

1. OAuth2 진행을 하며 추가했던 h2 console 부분을 해제해야 함

```java
@Bean
public WebSecurityCustomizer configure() {
    return (web) -> web.ignoring()
                    // .requestMatchers(toH2Console())
                       .requestMatchers("/img/**", "/css/**", "/js/**");
}
```

2. `application.yml` 수정
- AWS 환경과 port 번호(port = 5000) 맞추기
- datasource는 AWS RDS 엔드포인트 주소로 변경
- ddl-auto = none 설정으로 기존에 DB 서버에 생성해뒀던 테이블이 drop 되지 않도록 하기

```YAML
server:
  port: 5000

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: none
    defer-datasource-initialization: true

  datasource:
    url: {엔드포인트}:{포트번호}/{초기 데이터베이스 이름}
    username: admin
    password: ****

  config:
    import: classpath:application-oauth2.yml
```

3. 구글 클라우드 플랫폼 → 콘솔로 접속해서 인증된 URI에 5000번 port 등록

4. OAuth2를 진행하며 table이 일부 변경되어 기존에 DB 서버에 생성했던 table column들과 데이터가 매칭되지 않아 에러 발생
→ 기존 table 모두 drop
→ 다시 column에 맞게 CREATE TABLE하고 더미 데이터 넣어서 확인

### ~~아직 해결되지 않은 문제~~ (해결 완료)
- intellij에 내장되어 있는 h2-console을 이용하면 controller에 @GetMapping("/projects")만 있으면 경로 뒤에 refresh_token 등이 붙었을 때 /projects로 redirect가 잘 되는데,
- AWS RDS에 연결하면 /projects 뒤에 refresh_token을 붙으면 /projects로 redirect되지 않고 `whitelabel server error`가 발생
